2025-04-03 18:53:29 - my_app - ERROR - Logging id:1 - [app.py:91]
